language: python
python:
  - "3.7"
  - "3.8"

# dependencies
install:
  - pip install coverage
  - pip install coveralls

# command to run
script:
  - coverage run --source=amtTimer -m unittest

after_success:
  - coveralls
